
SELECT 
PROPERTYTYPE	
,SOLDPRICE		
,PERIOD	
,YEAR	
,QUARTER	
,CLOSINGDATE	
,DOM	
,LISTPRICE	
,MLS	
,ADDRESS	
,Island	
,region	
,subregion
FROM PRUSQL.MLS.[TABLEAU].[WEBSITE_HOOD_STATS_BY_LAST_FULLMONTH] DAT
INNER JOIN LOOKUP.hood_to_subregion REG ON DAT.NEIGHBORHOOD = REG.HOOD
where year(closingdate) = 2016

